# Permalinks

# Setup
title:               Language Variation and Cognition Lab
tagline:            University of Pennsylvania
site.url:                 http://tammingalab.github.io
paginate:            1
baseurl:             

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Meredith Tamminga
  url:               https://www.meredithtamminga.com
  email:            Tamminga-lab@sas.upenn.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/TammingaLab/TammingaLab.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
