title: Language Variation and Cognition Lab

description: UPenn Linguistics research lab at the intersection of sociolinguistics and psycholinguistics 

url: "https://Tammingalab.github.io"

markdown: kramdown